spring:
  application:
    name: playground-asb
  cloud:
    stream:
      default-binder: servicebus
      bindings:
        echoListener-out-0:
          destination: echo
        echoListener-in-0:
          destination: echo
          group: test
      servicebus:
        default:
          producer:
            entity-type: topic
          consumer:
            entity-type: topic
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        subscription-id: ${AZURE_SUBSCRIPTION_ID}
      servicebus:
        namespace: ${AZURE_SERVICE_BUS_NAMESPACE}
        resource:
          resource-group: ${AZURE_SERVICE_BUS_RESOURCE_GROUP}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: warn
    com.azure: info
    "com.github.ahrytsiuk.playground": info
