spring:
  application:
    name: playground-asb
  cloud:
    stream:
      default-binder: servicebus
      bindings:
        echoListener-out-0:
          destination: echo
        echoListener-in-0:
          destination: echo
          group: test
      servicebus:
        default:
          producer:
            entity-type: topic
          consumer:
            entity-type: topic
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        subscription-id: ${AZURE_SUBSCRIPTION_ID}
      servicebus:
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
        resource:
          resource-group: ${AZURE_SERVICEBUS_RESOURCE_GROUP}
